{% set version = "3.20.6" %}

package:
  name: libdap4
  version: {{ version }}

source:
  url: https://github.com/OPENDAP/libdap4/archive/version-{{ version }}.tar.gz
  sha256: e44e83043c158d8c9d0a37a1821626ab0db4a1a6578b02182440170c0b060e6d

build:
  number: 5
  skip: true  # [win]
  run_exports:
    # Seems to break ABI on some point releases
    # see https://abi-laboratory.pro/?view=timeline&l=libdap
    - {{ pin_subpackage('libdap4', max_pin='x.x.x') }}

requirements:
  build:
    - automake
    - autoconf
    - libtool
    - flex
    - bison
    - make  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - libxml2
    - curl
    - libuuid  # [not osx]
    - flex
    - zlib
  run:
    - libxml2
    - curl
    - libuuid  # [not osx]

test:
  commands:
    - dap-config --version
    - test -f ${PREFIX}/lib/libdap${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libdap.a
    - test -f ${PREFIX}/lib/libdapclient${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libdapclient.a
    - test -f ${PREFIX}/lib/libdapserver${SHLIB_EXT}
    - test ! -f ${PREFIX}/lib/libdapserver.a

about:
  home: http://www.opendap.org
  license: GPL-2.0-or-later
  license_file: COPYING
  summary: A C++ SDK which contains an implementation of both DAP2 and DAP4

extra:
  recipe-maintainers:
    - aleksandervines
    - jakirkham
    - ocefpaf
    - msarahan
