travis:
  secure:
    BINSTAR_TOKEN: Boe3kjXrvj8PC2pgnkhWK8/GX+W4mZTMlSUdjB50Dt2ArkFwyT0ngrv/XkmEiPw4GFZU6Wbam1Zl/ra6ozu26KhOaP/dxuF/+2bL/ystTVX075BaDfYVTIRZeMJnaIrWIWPzgDZCn5XAZgJM2NYSWB9ngYbPaelNzW/NIQkel4xI00y1BxCWPblO7SSymp/zk2HbaTZkUr4HGLwyOIiKqpjGnxdDr1E3kBPd3WsU1xtKvUuQWw/nwJ3bBfdaE14BOaST+UW59Jz8C6b6ptNh7NgeF1RJfdcufY4luKhuF6iZdvIfYQnac9OMUYkUjNwrU7+QqxBIYb3SXc9DpI20TlgyQn3dLjie1gAlikSO6mxjTnGbXuGj66JFtsgiCUbv3pdy9FCXYDg7ewO+5L/3KRDilop5EdkV6WtdVSVMIJ6/oZE2WTZtIsMV2AdLfMXZkSqcL3bas975ybywB9dRAThIuq0ufojKxVjbMzcf7Uhl6b+GPVDSpEbWY/7YO2ZtQ+OlzYVEpCCuxN4z5iglhJNfQlTaW71T+b2ANFCHHyX0iqViHB1VI29ZykLgkgMPKUQ9lXum/qkqSNTFxC0ytw0OJDbnPMJQlh7+fD1l1TtA/FFxcrqxnlzUA1wy4HXiByvMCb2qLkx4ljT3QXl0Bx8sTELhZCRznzeWiTaE4es=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
